#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serrate.Shipping.UI.Views.ShippingOrder
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ShippingOrder/ShippingAddress.cshtml")]
    public class ShippingAddress : System.Web.Mvc.WebViewPage<Serrate.Shipping.UI.Models.ShippingAddress>
    {
        public ShippingAddress()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n<div>\r\n    <div>     \r\n        Name: <span><b>");


            
            #line 5 "..\..\Views\ShippingOrder\ShippingAddress.cshtml"
                  Write(Html.DisplayFor(m => m.Fullname));

            
            #line default
            #line hidden
WriteLiteral("</b></span><br />\r\n        Address: <span><b>");


            
            #line 6 "..\..\Views\ShippingOrder\ShippingAddress.cshtml"
                     Write(Html.DisplayFor(m => m.Address));

            
            #line default
            #line hidden
WriteLiteral("</b></span><br />\r\n        City: <span><b>");


            
            #line 7 "..\..\Views\ShippingOrder\ShippingAddress.cshtml"
                  Write(Html.DisplayFor(m => m.City));

            
            #line default
            #line hidden
WriteLiteral("</b></span><br /><br />\r\n        <button id=\"btn1\">Change your shipping address</" +
"button><br /><br />\r\n    </div>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
