#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serrate.Sales.UI.Views.FinishOrder
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/FinishOrder/SubmitOrCancel.cshtml")]
    public class SubmitOrCancel : System.Web.Mvc.WebViewPage<dynamic>
    {
        public SubmitOrCancel()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<div>\r\n    <b>That\'s the final step for the Order with Id: ");


            
            #line 3 "..\..\Views\FinishOrder\SubmitOrCancel.cshtml"
                                               Write(ViewBag.OrderId);

            
            #line default
            #line hidden
WriteLiteral("</b>\r\n    <br /><br />\r\n");


            
            #line 5 "..\..\Views\FinishOrder\SubmitOrCancel.cshtml"
     using (Html.BeginForm("SubmitOrder", "FinishOrder")) {

            
            #line default
            #line hidden
WriteLiteral("        <input type=\"submit\" value=\"Submit Order\" />\r\n");


            
            #line 7 "..\..\Views\FinishOrder\SubmitOrCancel.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 9 "..\..\Views\FinishOrder\SubmitOrCancel.cshtml"
     using (Html.BeginForm("CancelOrder", "FinishOrder")) {

            
            #line default
            #line hidden
WriteLiteral("        <input type=\"submit\" value=\"Cancel Order\" />\r\n");


            
            #line 11 "..\..\Views\FinishOrder\SubmitOrCancel.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>");


        }
    }
}
#pragma warning restore 1591
